# Generated by Django 5.2.5 on 2025-08-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="current_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="idea",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
