# Generated by Django 5.2.5 on 2025-08-21 02:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idea',
            name='stage',
            field=models.CharField(choices=[('submitted', 'Submetido'), ('innovation_sector', 'Setor de Inovação'), ('responsible_manager', 'Gestor Responsável'), ('innovation_committee', 'Comitê de Inovação'), ('board_of_directors', 'Diretoria'), ('projects', 'Projetos'), ('implemented', 'Implementado')], default='submitted', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_analysis', 'Em Análise'), ('re_evaluation', 'Em Reavaliação'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Usuário'), ('admin', 'Administrador')], default='user', max_length=20),
        ),
    ]
