# Generated by Django 5.2.5 on 2025-08-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_idea_current_location_idea_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Enviado"),
                    ("in_department_review", "Em análise no departamento"),
                    ("in_committee_review", "Em análise no comitê"),
                    ("approved", "Aprovado"),
                    ("rejected", "Rejeitado"),
                    ("implemented", "Implementado"),
                ],
                default="submitted",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "Usuário"), ("admin", "Administrador")],
                default="user",
                max_length=10,
            ),
        ),
    ]
