# Generated by Django 5.2.5 on 2025-08-14 15:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_idea_status_alter_user_role"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", api.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="idea",
            name="stage",
            field=models.CharField(
                choices=[
                    ("submitted", "Submetido"),
                    ("innovation_sector", "Setor de Inovação"),
                    ("responsible_manager", "Gestor Responsável"),
                    ("innovation_committee", "Comitê de Inovação"),
                    ("board_of_directors", "Diretoria"),
                    ("projects", "Projetos"),
                    ("implemented", "Implementado"),
                ],
                default="submitted",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="idea",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("in_analysis", "Em Análise"),
                    ("re_evaluation", "Em Reavaliação"),
                    ("approved", "Aprovado"),
                    ("rejected", "Rejeitado"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
